### PR TITLE
add cobalt2 theme by wes bos

### PR DESCRIPTION
**Pull request by binyamin**
Added the theme. Is the difference between the header and the content too subtle?
image

### CODE REVIEW

**Comment by binyamin** [comment]
Also, @wesbos check it out!

**Comment by saurabhdaware** [comment]
Hey, that looks nice. Can you just change the header color a bit so it will be easier to differentiate between header and content?

**Comment by binyamin** [comment]
okay

**Comment by binyamin** [comment]
more? I'm trying to use the actual theme colors.

**Comment by saurabhdaware** [comment]
There is actually a darker color in theme I am not sure where I've seen it. I think a darker color would look nice on the header

**Comment by binyamin** [comment]
oh, on the header. I was thinking that, in terms of design, the content's background should be darker than the header. I'll take a look

**Comment by binyamin** [comment]
Thoughts? (I have changes I can push if you still want the header darker)
https://material.io/design/color/dark-theme.html
> ## Higher elevation, lighter surface
> The higher a surface’s elevation (raising it closer to an implied light source), the lighter that surface becomes. That lightness is expressed through the application of a semi-transparent overlay using the On Surface color.

**Review by saurabhdaware — APPROVED** [review]
Hey, this one looks really cool! Thank you so much! This will be the part of the next minor version 🌻

**Comment by binyamin** [comment]
Thank you

**Pull request merged**
